import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const workspaceDir = process.cwd();
const skillDir = 'C:/Users/manish_k/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations';
const tmpDir = path.join(workspaceDir, '.codex-build', 'saqshi-client-deck');
const finalPath = path.join(workspaceDir, 'output', 'presentations', 'Saqshi_Client_Presentation.pptx');
const { resolvePresentationFont, finalizePresentation } = await import(pathToFileURL(path.join(skillDir, 'container_tools/artifact_tool_utils.mjs')).href);
const font = resolvePresentationFont({ fontFamily: 'Aptos' });
const p = Presentation.create({ slideSize: { width: 1280, height: 720 } });
const C = { navy:'#102A43', blue:'#2563EB', teal:'#0F766E', coral:'#EF5B3F', ink:'#172B4D', muted:'#52627A', pale:'#F4F7FB', line:'#D9E2EF', white:'#FFFFFF', green:'#12805C', amber:'#D97706' };

function box(s, x,y,w,h, fill='none', radius='rect') { return s.shapes.add({ geometry:radius, position:{left:x,top:y,width:w,height:h}, fill, line:{fill:'none',width:0} }); }
function txt(s, value, x,y,w,h, size=20, color=C.ink, bold=false, align='left') { const a=box(s,x,y,w,h); a.text=value; a.text.style={typeface:font,fontSize:size,color,bold,autoFit:'shrinkText',paragraphAlignment:align,verticalAlignment:'middle',marginLeft:0,marginRight:0,marginTop:0,marginBottom:0}; return a; }
function title(s, t, sub='') { txt(s,t,72,42,1136,52,32,C.navy,true); if(sub) txt(s,sub,72,98,1020,30,17,C.muted); }
function footer(s,n) { txt(s,'SaQshi  |  Client presentation',72,682,320,18,11,C.muted); txt(s,String(n).padStart(2,'0'),1160,682,48,18,11,C.muted,false,'right'); }
async function image(s,file,x,y,w,h,fit='cover') { const bytes=await fs.readFile(file); return s.images.add({blob:bytes,contentType:'image/png',alt:'SaQshi presentation visual',fit,position:{left:x,top:y,width:w,height:h}}); }
function notes(s,t){ s.speakerNotes.textFrame.setText(t); }

const cover=path.join(workspaceDir,'output','presentations','saqshi-quality-review-cover.png');
const logo=path.join(workspaceDir,'ui','assets','images','logo1.png');
const team=path.join(workspaceDir,'ui','assets','images','landing-facility-team-digital.png');

{ const s=p.slides.add(); s.background.fill=C.white; await image(s,cover,0,0,1280,720); box(s,0,0,740,720,{color:C.white,transparency:5}); box(s,0,0,740,720,{color:C.navy,transparency:15}); await image(s,logo,74,55,180,52,'contain'); txt(s,'SaQshi',74,205,450,72,54,C.white,true); txt(s,'Digital quality assessment, continuous improvement and monitoring for public health facilities',74,292,510,100,27,C.white,false); txt(s,'Client presentation',74,600,220,25,16,'#DCE8F5'); txt(s,'Open-source platform maintained by Tech4Gov, Piramal Swasthya',74,634,520,25,14,'#DCE8F5'); notes(s,'Source: SaQshi About page and Project Overview. Cover image generated for this presentation; illustrative only.'); }

{ const s=p.slides.add(); s.background.fill=C.pale; title(s,'Quality work needs one connected workflow','SaQshi replaces disconnected assessment records with an accountable improvement cycle'); const rows=[['Assessment evidence','Checklist responses, department scope and assessor details remain connected to each facility assessment.'],['Improvement follow-through','Gaps become assigned action plans with target dates, evidence and closure updates.'],['Programme visibility','Monitoring users can review progress across block, district, division and state scope.']]; rows.forEach((r,i)=>{ const y=170+i*150; box(s,72,y,82,82,C.blue,'roundRect'); txt(s,String(i+1),72,y,82,82,30,C.white,true,'center'); txt(s,r[0],190,y,360,32,24,C.navy,true); txt(s,r[1],190,y+42,800,70,18,C.muted); }); txt(s,'Designed for facility-level quality data. Patient-level clinical records do not belong in SaQshi.',72,630,1040,28,16,C.teal,true); footer(s,2); notes(s,'Source: docs/architecture/project_overview.md and docs/user/user_guide.md.'); }

{ const s=p.slides.add(); s.background.fill=C.white; title(s,'Assessment to continuous quality improvement','A single record connects baseline findings with corrective action and monitoring'); const steps=[['1','Start or continue assessment'],['2','Activate applicable departments'],['3','Capture checklist responses'],['4','Review gaps and assign actions'],['5','Close gaps with evidence and revised score'],['6','Monitor reports, KPIs and certification']]; const y=266; box(s,100,y+30,1080,4,C.line); steps.forEach((a,i)=>{ const x=88+i*184; box(s,x,y,64,64,i===0?C.coral:C.blue,'ellipse'); txt(s,a[0],x,y,64,64,22,C.white,true,'center'); txt(s,a[1],x-28,y+88,120,62,16,C.ink,true,'center'); }); txt(s,'Scores support the workflow: 0 = non-compliance, 1 = partial compliance, 2 = full compliance',172,505,936,34,18,C.muted,false,'center'); await image(s,team,930,126,248,110,'cover'); footer(s,3); notes(s,'Source: docs/architecture/project_overview.md and docs/user/user_guide.md. Product image is from the workspace.'); }

{ const s=p.slides.add(); s.background.fill=C.pale; title(s,'Role-based experience for every level','Each role sees the workflow and geography that match its responsibility'); const roles=[['Facility team','Create assessments, complete checklists, manage CQI actions, enter KPI and outcome data.'],['Assessor','Work only on assigned facilities and allocated departments or classes.'],['Block, district and division','Monitor facilities within the assigned administrative area.'],['State administration','Monitor statewide data, manage assessors and users, track certification and export reports.']]; roles.forEach((r,i)=>{const col=i%2,row=Math.floor(i/2),x=72+col*570,y=165+row*205; box(s,x,y,510,158,C.white,'roundRect'); box(s,x,y,12,158,i<2?C.coral:C.teal); txt(s,r[0],x+38,y+26,420,30,23,C.navy,true); txt(s,r[1],x+38,y+70,420,62,17,C.muted);}); footer(s,4); notes(s,'Source: docs/user/user_guide.md, “Main User Types” and “State Monitoring”.'); }

{ const s=p.slides.add(); s.background.fill=C.white; title(s,'Core capabilities','The platform brings quality assessment and programme monitoring into the same operating model'); const capabilities=[['Structured assessment','Configurable frameworks, department activation, assessor information and checkpoint-level scoring.'],['CQI management','Gap analysis, action plans, responsible person, target date, closure remarks and evidence.'],['Performance monitoring','Configurable KPI and outcome indicators, monthly entry, formula-based results and trends.'],['Certification tracking','State or national certification status, history, validity, expiry tracking and map view.'],['Reports and exports','Scorecards, progress reports, CQI reports, performance downloads and state reports.']]; capabilities.forEach((r,i)=>{ const x=72+(i%2)*570,y=150+Math.floor(i/2)*152; box(s,x,y,510,118,i===4?'#EEF5FF':C.pale,'roundRect'); txt(s,r[0],x+24,y+20,440,28,21,C.navy,true); txt(s,r[1],x+24,y+58,440,45,16,C.muted); }); footer(s,5); notes(s,'Source: docs/architecture/project_overview.md, “Current Functional Scope”.'); }

{ const s=p.slides.add(); s.background.fill=C.pale; title(s,'Monitoring that supports action','Programme teams can move from an overview to the facility and checkpoint that require follow-up'); const left=[['Assessment progress','Track started, in-progress and completed assessments within the user’s scope.'],['CQI action tracking','Identify high-priority, unassigned, overdue and soon-due actions.'],['Risk analysis','Find the quality concerns affecting the most facilities and drill down by location, facility type and department.']]; left.forEach((r,i)=>{let y=158+i*145; txt(s,r[0],72,y,430,28,23,C.navy,true); txt(s,r[1],72,y+38,440,65,17,C.muted);}); box(s,610,150,566,420,C.navy,'roundRect'); txt(s,'State Facility Insights Map',650,190,420,34,26,C.white,true); txt(s,'View facility presence, certification coverage or the latest assessment result by Area of Concern and subtype.',650,245,400,80,18,'#DCE8F5'); [['Critical','0–25%',C.coral],['Needs improvement','26–60%',C.amber],['Satisfactory','Above 60%',C.green]].forEach((r,i)=>{let y=360+i*56;box(s,650,y,16,16,r[2],'ellipse');txt(s,r[0],682,y-3,180,24,17,C.white,true);txt(s,r[1],988,y-3,120,24,17,'#DCE8F5',false,'right');}); footer(s,6); notes(s,'Source: docs/user/user_guide.md and ui/help/state-risk-analysis.html; score bands from ui/help/state-facility-insights-map.html.'); }

{ const s=p.slides.add(); s.background.fill=C.white; title(s,'Designed for deployment and governance','Saqshi keeps the platform adaptable while making its data boundary explicit'); const items=[['Configurable by design','Frameworks, departments, performance indicators, certification rules and map settings use configuration files.'],['Facility-level data boundary','The platform supports facility observations, scores, CQI activity, KPI/outcome numbers and monitoring reports.'],['Protected administration','Role-based scopes restrict monitoring views. Administrative identity fields receive field encryption where implemented.'],['Open-source foundation','The platform is maintained by the Tech4Gov team at Piramal Swasthya.']]; items.forEach((r,i)=>{ const x=i%2?674:72,y=i>1?385:166; box(s,x,y,534,146,C.pale,'roundRect'); txt(s,r[0],x+26,y+24,465,28,22,C.navy,true); txt(s,r[1],x+26,y+62,465,60,17,C.muted);}); footer(s,7); notes(s,'Source: docs/architecture/project_overview.md and ui/help/about.html.'); }

{ const s=p.slides.add(); s.background.fill=C.navy; await image(s,logo,72,64,180,52,'contain'); txt(s,'A practical path to a SaQshi rollout',72,175,900,54,38,C.white,true); const steps=[['Confirm programme scope','Agree facility types, assessment framework, indicators and reporting needs.'],['Configure and validate','Set up masters, role mapping, geography, checklists and acceptance checks.'],['Pilot with real teams','Run a controlled facility pilot and refine workflow, reports and support.'],['Scale with oversight','Use dashboards, CQI tracking and certification views to guide follow-up.']]; steps.forEach((r,i)=>{let y=280+i*86; box(s,72,y,44,44,C.coral,'ellipse');txt(s,String(i+1),72,y,44,44,18,C.white,true,'center');txt(s,r[0],140,y,300,25,20,C.white,true);txt(s,r[1],454,y,650,45,16,'#DCE8F5');}); txt(s,'For partnership, implementation or technical support: tech4gov@piramalswasthya.org',72,654,950,28,16,'#DCE8F5'); footer(s,8); notes(s,'Contact source: ui/help/about.html. Rollout steps are a proposed implementation approach, not a product claim.'); }

await fs.mkdir(path.dirname(finalPath),{recursive:true});
const candidatePath=path.join(tmpDir,'candidate.pptx');
await (await PresentationFile.exportPptx(p)).save(candidatePath);
await finalizePresentation({workspaceDir,candidatePath,finalPath,pythonExecutable:'C:/Users/manish_k/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',integrityValidatorPath:path.join(skillDir,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skillDir,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit'],explicitTotalSlideCount:8,fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:path.join(tmpDir,'validation.json')});
