import fs from 'node:fs/promises'; import path from 'node:path';
import { Presentation, PresentationFile } from '@oai/artifact-tool';
const root=process.cwd(),out=path.join(root,'output','presentations','Saqshi_Client_Proposal_Healthcare.pptx');
const P=Presentation.create({slideSize:{width:1280,height:720}}), F='Aptos';
const C={navy:'#102B43',green:'#2E786F',orange:'#F68B25',blue:'#3478F6',mint:'#E8F5F0',pale:'#F4F7FA',line:'#D7E1EA',ink:'#193B5B',muted:'#5E7488',white:'#FFFFFF',rose:'#FDECEF',lav:'#F1EDFF'};
const box=(s,x,y,w,h,fill='none',g='rect')=>s.shapes.add({geometry:g,position:{left:x,top:y,width:w,height:h},fill,line:{fill:'none',width:0}});
function t(s,v,x,y,w,h,z=18,c=C.ink,b=false,a='left'){let q=box(s,x,y,w,h);q.text=v;q.text.style={typeface:F,fontSize:z,color:c,bold:b,autoFit:'shrinkText',paragraphAlignment:a,verticalAlignment:'middle',marginLeft:0,marginRight:0,marginTop:0,marginBottom:0};return q}
async function pic(s,file,x,y,w,h,fit='cover'){let b=await fs.readFile(file);s.images.add({blob:b,contentType:'image/png',alt:'SaQshi visual',fit,position:{left:x,top:y,width:w,height:h}})}
function hdr(s,k,title,sub,n){s.background.fill=C.pale;box(s,60,22,210,29,C.green,'roundRect');t(s,k,60,22,210,29,10,C.white,true,'center');t(s,title,60,57,1095,46,31,C.ink,true);box(s,60,100,77,5,C.orange);t(s,sub,60,125,1080,32,16,C.muted);box(s,0,686,1280,34,C.navy);t(s,'SaQshi | Client proposal',60,691,280,15,10,C.white);t(s,String(n).padStart(2,'0'),1200,691,30,15,10,C.white,false,'right')}
const cover=path.join(root,'output','presentations','saqshi-quality-review-cover.png'),logo=path.join(root,'ui','assets','images','logo1.png'),team=path.join(root,'ui','assets','images','landing-facility-team-digital.png');
// 1
{let s=P.slides.add();s.background.fill=C.navy;await pic(s,cover,0,0,1280,720);box(s,0,0,700,720,{color:C.navy,transparency:12});await pic(s,logo,70,56,180,56,'contain');t(s,'SaQshi',70,205,470,65,54,C.white,true);t(s,'A digital platform for facility quality assessment, continuous improvement and programme monitoring',70,290,500,112,27,C.white);t(s,'Client proposal | Public health facilities',70,602,420,24,16,'#DCE8F5');t(s,'Assess. Improve. Monitor. Report.',70,634,400,25,16,'#DCE8F5',true);s.speakerNotes.textFrame.setText('Source: SaQshi documentation. Cover image is illustrative.');}
// 2
{let s=P.slides.add();hdr(s,'CLIENT CONTEXT','Quality work loses momentum when the workflow breaks','Facility teams, assessors and programme managers often work across disconnected registers, spreadsheets and follow-up calls.',2);[['Assessments are hard to track','Teams need to know what started, what is incomplete and where evidence sits.'],['Gaps do not become action','A weak checkpoint needs a named action, owner, target date and closure evidence.'],['Leaders lack a single view','Programme teams need to see progress and risk at facility, district and state levels.']].forEach((r,i)=>{let x=72+i*392;box(s,x,210,356,275,C.white,'roundRect');box(s,x+24,234,50,50,[C.orange,C.blue,C.green][i],'ellipse');t(s,String(i+1),x+24,234,50,50,19,C.white,true,'center');t(s,r[0],x+24,310,300,45,21,C.ink,true);t(s,r[1],x+24,370,300,80,16,C.muted)});t(s,'SaQshi keeps the assessment, the improvement action and the monitoring view in the same platform.',135,566,1010,46,20,C.navy,true,'center');}
//3
{let s=P.slides.add();hdr(s,'THE PLATFORM','SaQshi turns quality assessment into an operating cycle','It gives each role the right workflow and connects field-level action with programme-level oversight.',3);await pic(s,team,753,194,447,316);[['ASSESS','Use configurable checklists to capture facility evidence and checkpoint scores.'],['IMPROVE','Convert gaps into action plans, assign ownership and record closure evidence.'],['MONITOR','Track assessment progress, overdue actions, performance and certification across geography.']].forEach((r,i)=>{let y=195+i*120;box(s,72,y,575,92,[C.mint,'#EAF2FF',C.lav][i],'roundRect');t(s,r[0],96,y+16,140,24,16,[C.green,C.blue,'#7657F6'][i],true);t(s,r[1],96,y+46,500,31,16,C.muted)});}
//4
{let s=P.slides.add();hdr(s,'FACILITY WORKFLOW','One assessment record carries the team from baseline to follow-up','Each step uses the same facility and assessment context, so teams can resume work and managers can trace progress.',4);const a=[['1','Create assessment'],['2','Activate departments'],['3','Record checklist scores'],['4','Review gaps'],['5','Assign actions'],['6','Close gaps with evidence']];box(s,110,302,1060,4,C.line);a.forEach((r,i)=>{let x=85+i*190;box(s,x,270,64,64,i===0?C.orange:C.blue,'ellipse');t(s,r[0],x,270,64,64,20,C.white,true,'center');t(s,r[1],x-28,355,120,50,16,C.ink,true,'center')});box(s,176,500,928,66,C.mint,'roundRect');t(s,'The reported score and progress reflect the assessment responses and the CQI closure record.',210,520,860,28,18,C.navy,true,'center');}
//5
{let s=P.slides.add();hdr(s,'ASSESSMENT','Structured assessment for real facility work','SaQshi supports configurable frameworks and department-aware checklist entry for a disciplined, auditable assessment process.',5);[['Framework and facility scope','Select the framework and activate only the departments that apply.'],['Checkpoint-level response','Record compliance at each checkpoint. In the NQAS profile: 0 non-compliance, 1 partial, 2 full.'],['Pause and continue','Teams can resume an active assessment instead of re-entering completed work.'],['Evidence and validation','Attach approved evidence and apply workflow rules to prevent incomplete or duplicate entry.']].forEach((r,i)=>{let x=i%2?672:72,y=i>1?390:195;box(s,x,y,536,142,C.white,'roundRect');box(s,x+23,y+24,44,44,[C.orange,C.blue,C.green,'#7657F6'][i],'ellipse');t(s,String(i+1),x+23,y+24,44,44,16,C.white,true,'center');t(s,r[0],x+88,y+24,400,24,19,C.ink,true);t(s,r[1],x+88,y+61,405,54,15,C.muted)});}
//6
{let s=P.slides.add();hdr(s,'CONTINUOUS QUALITY IMPROVEMENT','Every weak checkpoint becomes a managed improvement action','SaQshi maintains the corrective-action trail with the score that created it.',6);const a=[['Gap analysis','Non-compliance and partial-compliance checkpoints appear for review.'],['Action plan','Capture the responsible person, target date and the corrective action.'],['Closure','Add closure remarks, evidence and revised score where applicable.'],['Follow-up','Monitoring users can identify overdue, unassigned and high-priority actions.']];box(s,130,305,1020,4,C.line);a.forEach((r,i)=>{let x=94+i*282;box(s,x,264,76,76,[C.orange,C.blue,C.green,'#7657F6'][i],'ellipse');t(s,String(i+1),x,264,76,76,22,C.white,true,'center');t(s,r[0],x-20,370,116,25,18,C.ink,true,'center');t(s,r[1],x-28,409,135,70,14,C.muted,false,'center')});}
//7
{let s=P.slides.add();hdr(s,'MONITORING','Programme teams see where follow-up is needed','Role-based monitoring moves from an overview to the facility, department or checkpoint that needs attention.',7);[['Assessment coverage','Started, in-progress and completed assessment counts for the user’s geography.'],['CQI action tracking','Open, overdue, unassigned and soon-due actions for practical follow-up.'],['Risk analysis','Identify quality concerns affecting the greatest number of facilities, then drill down.'],['Facility insights','View facility presence, certification coverage and latest assessment risk by Area of Concern.']].forEach((r,i)=>{let x=i%2?672:72,y=i>1?390:195;box(s,x,y,536,142,[C.mint,'#EAF2FF',C.lav,C.rose][i],'roundRect');t(s,r[0],x+26,y+24,470,27,20,C.ink,true);t(s,r[1],x+26,y+63,460,47,15,C.muted)});}
//8
{let s=P.slides.add();hdr(s,'ROLE-BASED EXPERIENCE','Every user works at the right level','The platform separates facility data entry from monitoring responsibilities while preserving one connected record.',8);[['Facility team','Create assessments, complete checklists, manage CQI actions, enter KPI/outcome data and use facility reports.'],['Assessor','Work only on assigned facilities and allocated departments or classes.'],['Block, district and division','Monitor facility progress, CQI and performance within the assigned geography.'],['State administration','Monitor statewide data, certification and reports; manage assessors and users.']].forEach((r,i)=>{let x=i%2?672:72,y=i>1?386:190;box(s,x,y,536,150,C.white,'roundRect');box(s,x,y,10,150,i<2?C.orange:C.green);t(s,r[0],x+33,y+24,460,26,20,C.ink,true);t(s,r[1],x+33,y+65,455,61,15,C.muted)});}
//9
{let s=P.slides.add();hdr(s,'REPORTING AND PERFORMANCE','A client can monitor both quality activity and outcomes','SaQshi combines assessment reporting with monthly performance monitoring and certification tracking.',9);[['Reports','Scorecards, progress reports, CQI reports, performance downloads and state reports.'],['KPI and outcomes','Department-aware monthly entry, formula-based results and trend views.'],['Certification','State or national certification status, history, validity, expiry tracking and map view.']].forEach((r,i)=>{let x=72+i*392;box(s,x,213,356,283,[C.mint,'#EAF2FF',C.lav][i],'roundRect');box(s,x+26,240,56,56,[C.green,C.blue,'#7657F6'][i],'ellipse');t(s,String(i+1),x+26,240,56,56,20,C.white,true,'center');t(s,r[0],x+26,324,290,35,22,C.ink,true);t(s,r[1],x+26,377,290,80,16,C.muted)});}
//10
{let s=P.slides.add();hdr(s,'GOVERNANCE','Designed for facility-level quality data','The deployment scope focuses on facility observations, assessment scores, CQI actions, evidence, KPI/outcome numbers and monitoring reports.',10);[['No patient records required','SaQshi is not an electronic medical record or patient registry. It should not hold patient-level clinical information.'],['Configurable by design','Frameworks, departments, indicators, certification rules and map settings can be configured for an approved programme.'],['Controlled visibility','Role-based scope limits monitoring by geography and responsibility. Administrative identity fields receive protection where implemented.']].forEach((r,i)=>{let x=72+i*392;box(s,x,213,356,282,C.white,'roundRect');box(s,x+25,240,54,54,[C.orange,C.green,C.blue][i],'ellipse');t(s,String(i+1),x+25,240,54,54,19,C.white,true,'center');t(s,r[0],x+25,324,300,42,20,C.ink,true);t(s,r[1],x+25,384,300,80,16,C.muted)});}
//11
{let s=P.slides.add();hdr(s,'CLIENT VALUE','What changes when SaQshi becomes the operating platform','The value is practical: clearer work for teams, faster follow-up for managers and better visibility for programme leadership.',11);[['For facility teams','One guided workflow replaces separate records for assessment, action planning and closure.'],['For programme managers','Dashboard and report views show where coverage, action follow-up or performance needs attention.'],['For leadership','A consistent digital record supports accountability, reporting and future scale across facilities.']].forEach((r,i)=>{let y=191+i*135;box(s,72,y,1134,108,[C.mint,'#EAF2FF',C.lav][i],'roundRect');box(s,96,y+28,52,52,[C.green,C.blue,'#7657F6'][i],'ellipse');t(s,String(i+1),96,y+28,52,52,18,C.white,true,'center');t(s,r[0],180,y+20,280,25,20,C.ink,true);t(s,r[1],480,y+23,665,52,17,C.muted)});}
//12
{let s=P.slides.add();hdr(s,'IMPLEMENTATION','A controlled rollout proves the model before scale','The first implementation should focus on one agreed programme scope, a prepared user group and measurable operating outcomes.',12);[['Confirm programme scope','Agree facility types, geography, framework, indicators and client reporting needs.'],['Configure and validate','Set up master data, role mapping, workflow rules, checklists and monitoring views.'],['Pilot with real users','Run a controlled pilot with facility teams and monitoring users; refine support and reports.'],['Scale with governance','Use dashboards and CQI follow-up to guide adoption and staged expansion.']].forEach((r,i)=>{let y=185+i*100;box(s,72,y,48,48,C.orange,'ellipse');t(s,String(i+1),72,y,48,48,18,C.white,true,'center');t(s,r[0],145,y,275,26,19,C.ink,true);t(s,r[1],432,y,680,45,16,C.muted)});}
//13
{let s=P.slides.add();s.background.fill=C.navy;await pic(s,logo,70,63,180,56,'contain');t(s,'Let’s define the first SaQshi pilot',70,190,850,55,39,C.white,true);[['Programme and facility scope','Which facilities and framework should form the first cohort?'],['Client roles and reporting','Who will assess, act, monitor and receive programme reports?'],['Success measures','Which quality, process and adoption measures will define a successful pilot?']].forEach((r,i)=>{let y=300+i*94;box(s,70,y,46,46,C.orange,'ellipse');t(s,String(i+1),70,y,46,46,17,C.white,true,'center');t(s,r[0],142,y,300,24,19,C.white,true);t(s,r[1],468,y,600,42,16,'#DCE8F5')});t(s,'tech4gov@piramalswasthya.org',70,652,420,25,17,'#DCE8F5');s.speakerNotes.textFrame.setText('Contact source: ui/help/about.html.');}
await fs.mkdir(path.dirname(out),{recursive:true}); await (await PresentationFile.exportPptx(P)).save(out);console.log('created 13 slides');
