import fs from 'node:fs/promises';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const out = 'D:/sAQshi_new_27112025/SaQshi_open_source/saQshi_open_source/SaQshi_Education_Donor_Deck.pptx';
const img = 'D:/sAQshi_new_27112025/SaQshi_open_source/saQshi_open_source/ui/assets/images/landing-school-assessment.png';
const deck = Presentation.create({slideSize:{width:1280,height:720}});
const C={navy:'#0A2540',blue:'#146C94',sky:'#DDF3FA',gold:'#F3B83F',ink:'#102A43',muted:'#52677A',pale:'#F5FAFC',white:'#FFFFFF',green:'#13795B'};
async function blob(p){const b=await fs.readFile(p);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}
function box(s,x,y,w,h,fill,rad=0){return s.shapes.add({geometry:rad?'roundRect':'rect',position:{left:x,top:y,width:w,height:h},fill,line:{style:'solid',fill,width:0},borderRadius:rad?'rounded-xl':undefined});}
function text(s,t,x,y,w,h,size=24,color=C.ink,bold=false,align='left'){const q=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{style:'solid',fill:'none',width:0}});q.text=t;q.text.style={fontSize:size,color,bold,alignment:align,fontFace:'Arial'};return q;}
function top(s,n,title){text(s,'SAQSHI EDUCATION',64,42,280,26,14,C.blue,true);text(s,title,64,92,1030,56,38,C.navy,true);text(s,String(n).padStart(2,'0'),1165,48,48,24,14,C.muted,true,'right');}
function notes(s){s.speakerNotes.textFrame.setText('[Sources]\nSaQshi open-source repository: README.md and docs/architecture/project_overview.md.\nProduct image: ui/assets/images/landing-school-assessment.png.\n[/Sources]');}
function addBullets(s,items,x,y,w){items.forEach((it,i)=>{box(s,x,y+i*70,10,10,C.gold,5);text(s,it,x+24,y-8+i*70,w-25,52,22,C.ink,false);});}
const schoolImage=await blob(img);

{const s=deck.slides.add();s.background.fill=C.navy;box(s,0,0,1280,720,C.navy);box(s,64,74,10,460,C.gold);text(s,'SaQshi Education',98,98,740,80,54,C.white,true);text(s,'A digital quality-assessment and improvement platform for schools',98,198,690,86,28,'#D7E9F4',false);text(s,'A donor partnership opportunity to make school quality visible, actionable and scalable.',98,468,690,62,22,C.white,false);s.images.add({blob:schoolImage,contentType:'image/png',alt:'SaQshi school assessment interface',fit:'cover',position:{left:835,top:70,width:365,height:530},geometry:'roundRect',borderRadius:'rounded-xl'});text(s,'Open-source • Configurable • Field-ready',98,620,500,26,16,C.gold,true);notes(s);}
{const s=deck.slides.add();s.background.fill=C.white;top(s,2,'School quality work is often fragmented');text(s,'Programme teams need a single, trusted view of what is happening in schools.',64,172,800,42,24,C.muted);addBullets(s,['Assessments are difficult to standardise across schools and grades.','Findings can remain in paper forms, spreadsheets or disconnected files.','Follow-up actions and progress are hard to monitor across geography.'],90,260,760);box(s,920,210,230,285,C.sky,18);text(s,'The result',950,250,170,28,20,C.blue,true);text(s,'Limited visibility\nSlow follow-up\nUneven learning environments',950,310,180,130,24,C.navy,true);notes(s);}
{const s=deck.slides.add();s.background.fill=C.pale;top(s,3,'SaQshi turns assessment into a continuous improvement cycle');const steps=['Prepare','Assess','Prioritise','Act','Monitor'];steps.forEach((a,i)=>{const x=70+i*232;box(s,x,265,180,130,i===2?C.blue:C.white,18);text(s,String(i+1).padStart(2,'0'),x+18,284,45,20,14,i===2?C.gold:C.blue,true);text(s,a,x+18,326,145,34,24,i===2?C.white:C.navy,true);if(i<4)text(s,'→',x+190,313,36,35,28,C.gold,true,'center');});text(s,'A configurable workflow captures evidence, scores performance, identifies gaps and tracks closure over time.',100,505,1060,50,24,C.muted,false,'center');notes(s);}
{const s=deck.slides.add();s.background.fill=C.white;top(s,4,'One platform for assessors, school leaders and programme teams');const cols=[['Field assessor','Guided checklist\nSave and resume\nStructured responses'],['School leader','Clear gaps\nAction ownership\nEvidence-based follow-up'],['Programme team','School-to-state view\nProgress monitoring\nDownloadable reports']];cols.forEach((c,i)=>{const x=64+i*385;box(s,x,210,340,285,C.pale,18);text(s,c[0],x+26,248,280,34,26,C.navy,true);text(s,c[1],x+26,320,280,115,22,C.muted,false);});text(s,'Role-based access connects action at the school with oversight across blocks, districts and the state.',115,560,1040,35,23,C.blue,true,'center');notes(s);}
{const s=deck.slides.add();s.background.fill=C.navy;top(s,5,'Designed to work where connectivity is unreliable');text(s,'Offline-ready assessment protects field progress.',70,185,600,52,32,C.white,true);addBullets(s,['Responses can be saved on the device during a network interruption.','Pending responses synchronise when connectivity returns.','A mobile app pathway can strengthen continuity beyond the browser.'],90,290,610);box(s,760,175,380,340,'#113B5D',18);text(s,'Field confidence',798,222,280,30,22,C.gold,true);text(s,'Assessors can continue their work rather than losing progress to a connection failure.',798,285,278,115,25,C.white,true);notes(s);}
{const s=deck.slides.add();s.background.fill=C.white;top(s,6,'Donor support can take SaQshi Education from platform to programme');const rows=[['1. Pilot','Adapt the framework, onboard schools and train assessors.'],['2. Learn','Use data to improve the workflow, dashboards and support model.'],['3. Scale','Expand to priority geographies with evidence-based governance.']];rows.forEach((r,i)=>{const y=205+i*115;box(s,70,y,1060,82,i===1?C.sky:C.pale,14);text(s,r[0],95,y+22,150,30,23,C.navy,true);text(s,r[1],300,y+20,770,40,21,C.muted,false);});notes(s);}
{const s=deck.slides.add();s.background.fill=C.pale;top(s,7,'A partnership can create measurable public value');const vals=[['Consistency','A common assessment approach across participating schools'],['Accountability','Clear ownership for gaps, actions and follow-up'],['Visibility','Timely reporting for programme decisions'],['Reusability','Open-source, configurable technology for future programmes']];vals.forEach((v,i)=>{const x=70+(i%2)*560,y=205+Math.floor(i/2)*170;box(s,x,y,505,125,C.white,16);text(s,v[0],x+25,y+24,420,30,24,C.blue,true);text(s,v[1],x+25,y+66,420,45,19,C.muted,false);});notes(s);}
{const s=deck.slides.add();s.background.fill=C.navy;text(s,'A practical next step',70,90,800,58,42,C.white,true);text(s,'Fund a focused pilot that proves how digital quality assessment can help schools move from observation to improvement.',70,190,810,95,28,'#D7E9F4');box(s,70,355,620,2,C.gold);text(s,'Pilot discussion',70,402,260,30,20,C.gold,true);text(s,'Define the geography, assessment framework, partners and success measures together.',70,448,650,58,24,C.white,false);text(s,'SaQshi Education',70,620,500,30,20,C.white,true);notes(s);}
const pptx=await PresentationFile.exportPptx(deck);await pptx.save(out);
