<?php

/**
 * Csrf.php
 * -------------------------------------------------------
 * CSRF Protection for SaQshi APIs
 *
 * Client must send:
 * X-CSRF-TOKEN: token
 *
 * OR
 * csrf_token in POST/JSON body
 * -------------------------------------------------------
 */

class Csrf
{
    private const SESSION_KEY = '_csrf_token';

    /**
     * Generate token if not exists.
     */
    public static function generate(): string
    {
        SessionManager::start();

        if (empty($_SESSION[self::SESSION_KEY])) {
            $_SESSION[self::SESSION_KEY] = bin2hex(random_bytes(32));
        }

        return $_SESSION[self::SESSION_KEY];
    }

    /**
     * Get current token.
     */
    public static function token(): string
    {
        return self::generate();
    }

    /**
     * Regenerate token.
     */
    public static function regenerate(): string
    {
        SessionManager::start();

        $_SESSION[self::SESSION_KEY] = bin2hex(random_bytes(32));

        return $_SESSION[self::SESSION_KEY];
    }

    /**
     * Validate token.
     */
    public static function validate(): void
    {
        SessionManager::start();

        $sessionToken = (string)($_SESSION[self::SESSION_KEY] ?? '');
        $requestToken = (string)self::extractRequestToken();

        /*
         * Normalize tokens.
         * Token is generated by bin2hex(random_bytes(32)),
         * so valid token must contain only 0-9 and a-f.
         */
        $sessionToken = preg_replace('/[^a-f0-9]/i', '', $sessionToken);
        $requestToken = preg_replace('/[^a-f0-9]/i', '', $requestToken);

        /*
         * IIS / browser issue handling:
         * If frontend sends hex-encoded hex string, length becomes 128.
         * Convert it back to normal 64-char token.
         */
        if (
            strlen($requestToken) === 128 &&
            ctype_xdigit($requestToken)
        ) {
            $decoded = hex2bin($requestToken);

            if ($decoded !== false) {
                $requestToken = preg_replace('/[^a-f0-9]/i', '', $decoded);
            }
        }

        if ($sessionToken === '') {
            self::fail('CSRF token missing from session', [
                'session_id' => session_id(),
                'has_session_token' => false,
                'has_header_token' => $requestToken !== ''
            ]);
        }

        if ($requestToken === '') {
            self::fail('CSRF token missing', [
                'session_id' => session_id(),
                'has_session_token' => true,
                'has_header_token' => false
            ]);
        }

        if (!hash_equals($sessionToken, $requestToken)) {
            self::fail('Invalid CSRF token', [
                'session_id' => session_id(),
                'session_len' => strlen($sessionToken),
                'request_len' => strlen($requestToken),
                'session_token_start' => substr($sessionToken, 0, 8),
                'request_token_start' => substr($requestToken, 0, 8),
                'session_token_end' => substr($sessionToken, -8),
                'request_token_end' => substr($requestToken, -8),
                'has_session_token' => true,
                'has_header_token' => true
            ]);
        }
    }

    /**
     * Return token information.
     */
    public static function getTokenInfo(): array
    {
        return [
            'csrf_token' => self::token(),
            'header_name' => 'X-CSRF-TOKEN'
        ];
    }

    /**
     * Extract token from request.
     */
    private static function extractRequestToken(): string
    {
        /*
         * IIS / Apache / Nginx normalized header.
         */
        if (!empty($_SERVER['HTTP_X_CSRF_TOKEN'])) {
            return trim((string)$_SERVER['HTTP_X_CSRF_TOKEN']);
        }

        if (!empty($_SERVER['HTTP_X_CSRF'])) {
            return trim((string)$_SERVER['HTTP_X_CSRF']);
        }

        /*
         * Fallback: getallheaders()
         */
        if (function_exists('getallheaders')) {
            $headers = getallheaders();

            foreach ($headers as $key => $value) {
                if (strtolower($key) === 'x-csrf-token') {
                    return trim((string)$value);
                }
            }
        }

        /*
         * POST body.
         */
        if (isset($_POST['csrf_token'])) {
            return trim((string)$_POST['csrf_token']);
        }

        /*
         * JSON body fallback.
         */
        $raw = file_get_contents('php://input');

        if (!empty($raw)) {
            $json = json_decode($raw, true);

            if (
                is_array($json) &&
                isset($json['csrf_token'])
            ) {
                return trim((string)$json['csrf_token']);
            }
        }

        return '';
    }

    /**
     * Destroy token.
     */
    public static function destroy(): void
    {
        SessionManager::start();

        unset($_SESSION[self::SESSION_KEY]);
    }

    /**
     * JSON error.
     */
    private static function fail(string $message, array $debug = []): never
    {
        http_response_code(403);

        echo json_encode([
            'status' => 'error',
            'message' => $message,
            'data' => null,
            'errors' => null,
            'debug' => $debug,
            'timestamp' => date('Y-m-d H:i:s')
        ]);

        exit;
    }
}