import fs from 'node:fs/promises';
import path from 'node:path';
import { FileBlob, PresentationFile } from '@oai/artifact-tool';
const root=process.cwd(), base=path.join(root,'.codex-build','saqshi-strong-deck');
const deck=await PresentationFile.importPptx(await FileBlob.load(path.join(base,'source.pptx')));
const font='Aptos'; const C={navy:'#173B5B',green:'#2E786F',orange:'#F68B25',muted:'#5F7488',pale:'#F4F7FA',line:'#D5DEE7',white:'#FFFFFF',blue:'#3478F6',mint:'#E8F5F0',lav:'#F2EDFF',rose:'#FDECEF'};
function shape(s,x,y,w,h,fill='none',geometry='rect'){return s.shapes.add({geometry,position:{left:x,top:y,width:w,height:h},fill,line:{fill:'none',width:0}})}
function text(s,v,x,y,w,h,size=18,color=C.navy,bold=false,align='left'){let a=shape(s,x,y,w,h);a.text=v;a.text.style={typeface:font,fontSize:size,color,bold,autoFit:'shrinkText',paragraphAlignment:align,verticalAlignment:'middle',marginLeft:0,marginRight:0,marginTop:0,marginBottom:0};return a}
async function img(s,file,x,y,w,h){const b=await fs.readFile(file);s.images.add({blob:b,contentType:'image/png',alt:'SaQshi brand logo',fit:'contain',position:{left:x,top:y,width:w,height:h}})}
function header(s,kicker,title,subtitle,n){s.background.fill=C.pale;shape(s,60,22,212,29,C.green,'roundRect');text(s,kicker,60,22,212,29,11,C.white,true,'center');text(s,title,60,57,1080,43,31,C.navy,true);shape(s,60,99,77,5,C.orange);text(s,subtitle,60,125,1080,28,16,C.muted);shape(s,0,686,1280,34,C.navy);text(s,'SaQshi | Open Digital Quality Improvement Platform',52,690,420,18,10,C.white);text(s,String(n),1200,690,30,18,11,C.white,false,'right')}
const logo=path.join(root,'ui','assets','images','logo1.png');
const team=path.join(root,'ui','assets','images','landing-facility-team-digital.png');
let s=deck.slides.add();header(s,'HEALTHCARE PLATFORM','SaQshi connects assessment, action and oversight','The health deployment brings assessment, CQI, performance monitoring, certification and reporting into one platform.',24);await img(s,logo,1142,34,88,31);await img(s,team,770,188,430,324);
[['Structured assessment','Create or resume assessments, activate applicable departments and capture checkpoint responses.'],['CQI action management','Turn gaps into action plans with ownership, target dates, evidence and closure updates.'],['Performance monitoring','Record monthly KPI and outcome data, calculate results and review trends.'],['Certification and reports','Track certification status and history, then use reports to support follow-up.']].forEach((r,i)=>{const x=72+(i%2)*330,y=190+Math.floor(i/2)*164;shape(s,x,y,292,128,[C.mint,'#EAF2FF',C.lav,C.rose][i],'roundRect');text(s,r[0],x+22,y+22,246,25,18,C.navy,true);text(s,r[1],x+22,y+57,246,53,14,C.muted)});s.speakerNotes.textFrame.setText('Source: docs/architecture/project_overview.md.');
s=deck.slides.add();header(s,'ROLE-BASED OPERATIONS','The right view for each person','SaQshi separates facility work from supervisory monitoring while keeping every assessment traceable to its scope.',25);await img(s,logo,1142,34,88,31);
const roles=[['Facility team','Assessment entry, CQI actions, evidence, KPI/outcome entry and facility reports.'],['Assessor','Assigned facility assessments and allocated department or class work.'],['District and division','Progress, CQI and performance monitoring for assigned geography.'],['State administration','Statewide dashboards, certification views, assessor management, exports and reports.']];roles.forEach((r,i)=>{let x=i%2?674:72,y=i>1?390:190;shape(s,x,y,534,146,C.white,'roundRect');shape(s,x,y,10,146,i<2?C.orange:C.green);text(s,r[0],x+33,y+23,460,25,19,C.navy,true);text(s,r[1],x+33,y+62,460,60,15,C.muted)});s.speakerNotes.textFrame.setText('Source: docs/user/user_guide.md.');
s=deck.slides.add();header(s,'CONTINUOUS QUALITY IMPROVEMENT','A score creates a clear next action','SaQshi keeps the corrective-action trail connected to the assessment result rather than separating it into files.',26);await img(s,logo,1142,34,88,31);
const flow=[['1','Score checklist','Non-compliance and partial-compliance checkpoints become gaps.'],['2','Set action plan','Assign responsible person and target date for each gap.'],['3','Add evidence','Attach supporting evidence and record closure remarks.'],['4','Review revised score','Use closure status and revised score in progress reports and monitoring.']];shape(s,130,309,1020,3,C.line);flow.forEach((r,i)=>{let x=95+i*282;shape(s,x,267,76,76,[C.orange,C.blue,'#2EB67D','#7A5AF8'][i],'ellipse');text(s,r[0],x,267,76,76,23,C.white,true,'center');text(s,r[1],x-20,370,115,27,17,C.navy,true,'center');text(s,r[2],x-28,407,135,63,14,C.muted,false,'center')});shape(s,170,545,940,63,C.mint,'roundRect');text(s,'Monitoring teams can identify open, overdue and high-priority actions without changing the facility’s underlying action plan.',205,563,870,25,16,C.navy,true,'center');s.speakerNotes.textFrame.setText('Source: docs/architecture/project_overview.md and docs/user/user_guide.md.');
s=deck.slides.add();header(s,'IMPLEMENTATION','A practical path to a SaQshi rollout','The platform supports local programme configuration. A client rollout begins by aligning its scope and operating model.',27);await img(s,logo,1142,34,88,31);
const rollout=[['Confirm scope','Agree facility types, geography, framework, indicators and reporting needs.'],['Configure platform','Set up masters, roles, workflow rules, checklist and monitoring views.'],['Pilot with users','Run a controlled pilot with facility teams and monitoring users, then refine.'],['Scale with governance','Use adoption support, dashboards and CQI follow-up to guide expansion.']];rollout.forEach((r,i)=>{let y=181+i*103;shape(s,72,y,48,48,C.orange,'ellipse');text(s,String(i+1),72,y,48,48,18,C.white,true,'center');text(s,r[0],146,y,265,25,19,C.navy,true);text(s,r[1],425,y,720,45,16,C.muted)});shape(s,72,616,1060,42,C.navy,'roundRect');text(s,'Client discussion: select the first programme, facilities and users for a focused pilot.',95,624,1015,24,16,C.white,true,'center');s.speakerNotes.textFrame.setText('Rollout structure is a proposed approach based on SaQshi configuration and role workflows.');
const candidate=path.join(base,'candidate.pptx');await (await PresentationFile.exportPptx(deck)).save(candidate);console.log('slides='+deck.slides.items.length);
